[build]
  publish = "build"
  command = "npm run build"

# Prefer setting REACT_APP_API_URL in Netlify UI (Site settings → Environment variables)
# This avoids baking preview URLs into commits.
# [build.environment]
#   REACT_APP_API_URL = "https://<your-backend-host>"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
