[build]
  base = "client"
  command = "npm run build"
  publish = "build"

# Prefer configuring REACT_APP_API_URL in Netlify UI so it isn't hardcoded to a preview URL
# If you really need to define it here, uncomment below and set to your stable backend domain
# [build.environment]
#   # No trailing slash; do NOT append /api here
#   REACT_APP_API_URL = "https://<your-vercel-project>.vercel.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# More info: https://ntl.fyi/file-based-build-config
